services:
  backend:
    build: ./backend
    container_name: star-crawler-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: star-crawler-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  db: 
    image: mariadb:11
    container_name: star-crawler-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starcrawler
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: star-crawler-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
